version: '3.8'
services:
  # Development override: mount code and use bootRun for instant reload
  api:
    image: gradle:7.6.1-jdk17
    working_dir: /home/gradle/project/api
    volumes:
      - ./api:/home/gradle/project/api
      - ~/.gradle:/home/gradle/.gradle
    command: gradle bootRun --no-daemon
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/binome_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: ChangeThisSecretKeyForDevOnly
      JWT_EXPIRATION_MS: 3600000
    depends_on:
      - db
  # Reuse the same DB service from docker-compose.yml
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: binome_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true