version: '3.8'
services:
  # Development override: mount code and use bootRun for instant reload
  api:
    image: gradle:7.6.1-jdk17
    working_dir: /home/gradle/project/api
    volumes:
      - ./api:/home/gradle/project/api
      - ./core:/home/gradle/project/core
      - ./security:/home/gradle/project/security
      - ./build.gradle:/home/gradle/project/build.gradle
      - ./settings.gradle:/home/gradle/project/settings.gradle
      - gradle-cache:/home/gradle/.gradle
    command: gradle bootRun --no-daemon --no-watch-fs
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/binome_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: ChangeThisSecretKeyForDevOnly
      JWT_EXPIRATION_MS: 3600000
      GRADLE_USER_HOME: /home/gradle/.gradle
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.vfs.watch=false"
    depends_on:
      - db
  # Reuse the same DB service from docker-compose.yml
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: binome_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true
  gradle-cache: