services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: binome_database
      POSTGRES_USER: postgres
      # WARNING: This is for development only. Use Docker secrets or environment variables in production
      POSTGRES_PASSWORD: dev_password_change_in_production
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/binome_database
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dev_password_change_in_production
      # JWT secret is properly externalized here - good practice!
      JWT_SECRET: ${JWT_SECRET:-dGhpcy1pcy1hLWRldmVsb3BtZW50LW9ubHktc2VjcmV0LWtleS1mb3ItYmlub21lLW1hdGNoZXItYXBwbGljYXRpb24td2hpY2gtc2hvdWxkLWJlLXJlcGxhY2VkLWluLXByb2R1Y3Rpb24=}
      JWT_EXPIRATION_MS: ${JWT_EXPIRATION_MS:-3600000}
    ports:
      - "8080:8080"

volumes:
  pgdata:
    driver: local